services:
    # olive-db:
    #     image: postgres
    #     container_name: olive-db
    #     volumes:
    #         - "olive_db:/var/lib/postgresql/data"
    #     # To log all statements
    #     # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    #     env_file:
    #         - .env
    #     ports:
    #         - "5432:5432"

    caddy:
        image: caddy:alpine
        restart: unless-stopped
        container_name: caddy
        ports:
            - 80:80
            - 443:443
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/site:/srv
            - caddy_data:/data
            - caddy_config:/config

    olive:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        container_name: olive
        env_file:
            - .env
        ports:
            - 3000:3000
        develop:
            watch:
                - action: sync+restart
                  path: ./
                  target: /app/
                - action: rebuild
                  path: ./pyproject.toml
                  target: /app/pyproject.toml

volumes:
    # olive_db:
    #     external: true
    caddy_data:
    caddy_config:

