"""empty message

Revision ID: c06b5cec40cc
Revises: 7cf29dd61f2c
Create Date: 2024-07-23 13:56:37.887932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06b5cec40cc'
down_revision: Union[str, None] = '7cf29dd61f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_customer_set',
    sa.Column('id', sa.Text(), server_default=sa.text("id_generator('campaign-customer-set')"), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('customer_set_id', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp_utc()'), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp_utc()'), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_set_id'], ['customer_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        """
        CREATE OR REPLACE TRIGGER set_timestamp_campaign_customer_set
        BEFORE UPDATE ON "campaign_customer_set"
        FOR EACH ROW
        EXECUTE FUNCTION trigger_set_timestamp_modify();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS set_timestamp_campaign_customer_set on "campaign_customer_set"')
    op.drop_table('campaign_customer_set')
    # ### end Alembic commands ###
