"""empty message

Revision ID: c3100f485556
Revises: c06b5cec40cc
Create Date: 2024-07-24 02:14:07.464359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3100f485556'
down_revision: Union[str, None] = 'c06b5cec40cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('id', sa.Text(), server_default=sa.text("id_generator('call')"), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('from_number', sa.Text(), nullable=False),
    sa.Column('to_number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telephony_service_id', sa.Text(), nullable=False),
    sa.Column('telephony_service_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transcriber_id', sa.Text(), nullable=False),
    sa.Column('transcriber_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('agent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synthesizer_id', sa.Text(), nullable=False),
    sa.Column('synthesizer_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp_utc()'), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp_utc()'), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['synthesizer_id'], ['synthesizer.id'], ),
    sa.ForeignKeyConstraint(['telephony_service_id'], ['telephony_service.id'], ),
    sa.ForeignKeyConstraint(['transcriber_id'], ['transcriber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        """
        CREATE OR REPLACE TRIGGER set_timestamp_call
        BEFORE UPDATE ON "call"
        FOR EACH ROW
        EXECUTE FUNCTION trigger_set_timestamp_modify();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION compute_call_duration()
        RETURNS trigger as $$
        BEGIN
            IF new.start_time IS NOT NULL AND new.end_time IS NOT NULL THEN
                new.duration = CEIL(EXTRACT(EPOCH FROM new.end_time - new.start_time));
            END IF;
            RETURN new;
        END;
        $$ language plpgsql;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE TRIGGER compute_duration
        BEFORE UPDATE ON "call"
        FOR EACH ROW
        EXECUTE FUNCTION compute_call_duration();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS set_timestamp_call on "call"')
    op.execute('DROP TRIGGER IF EXISTS compute_duration on "call"')
    op.execute('DROP FUNCTION IF EXISTS compute_call_duration')
    op.drop_table('call')
    # ### end Alembic commands ###
