"""empty message

Revision ID: 5ef9c0e64733
Revises: 
Create Date: 2022-09-21 12:47:45.625415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef9c0e64733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with open('migrations/functions/id_generator.sql', 'r') as fd:
        statements = fd.read()
        for statement in statements.split("--bun:split"):
            op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP FUNCTION IF EXISTS trigger_set_timestamp_modify')
    op.execute('DROP FUNCTION IF EXISTS current_timestamp_utc')
    op.execute('DROP FUNCTION IF EXISTS id_generator')
    op.execute('DROP SEQUENCE IF EXISTS global_id_sequence')
    # ### end Alembic commands ###
