"""empty message

Revision ID: 86947956f5ca
Revises: 9cce625057df
Create Date: 2024-07-21 02:14:32.252447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86947956f5ca'
down_revision: Union[str, None] = '9cce625057df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.String(), server_default=sa.text("id_generator('campaign')"), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='DRAFT', nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('max_duration', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('telephony_service_id', sa.String(), nullable=True),
    sa.Column('telephony_service_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcriber_id', sa.String(), nullable=True),
    sa.Column('transcriber_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('agent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synthesizer_id', sa.String(), nullable=True),
    sa.Column('synthesizer_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp_utc()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp_utc()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['synthesizer_id'], ['synthesizer.id'], ),
    sa.ForeignKeyConstraint(['telephony_service_id'], ['telephony_service.id'], ),
    sa.ForeignKeyConstraint(['transcriber_id'], ['transcriber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        """
        CREATE OR REPLACE TRIGGER set_timestamp_campaign
        BEFORE UPDATE ON "campaign"
        FOR EACH ROW
        EXECUTE FUNCTION trigger_set_timestamp_modify();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS set_timestamp_campaign on "campaign"')
    op.drop_table('campaign')
    # ### end Alembic commands ###
