"""empty message

Revision ID: 34dfab535ccf
Revises: afee87188d2e
Create Date: 2024-07-17 17:31:06.992420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34dfab535ccf'
down_revision: Union[str, None] = 'afee87188d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.String(), server_default=sa.text("id_generator('organization')"), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('telephony_service_id', sa.String(), nullable=False),
    sa.Column('telephony_service_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transcriber_id', sa.String(), nullable=False),
    sa.Column('transcriber_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synthesizer_id', sa.String(), nullable=False),
    sa.Column('synthesizer_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['synthesizer_id'], ['synthesizer.id'], ),
    sa.ForeignKeyConstraint(['telephony_service_id'], ['telephony_service.id'], ),
    sa.ForeignKeyConstraint(['transcriber_id'], ['transcriber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    # ### end Alembic commands ###
